<!DOCTYPE html>

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
   <b> <title>KTM</title> </b>
</head>

<body class="bg-success p-3">
    <table border="3">
        <tr>
            <td colspan="3">
                <center>KTM</center>
            </td>
        </tr>
        <tr>
            <td>Nama</td>
            <td>Woody</td>
            <td rowspan="10"><img width='110' src="woody.JPEG"></td>
        </tr>
        <tr>
            <td>NIM</td>
            <td>215314116</td>
        </tr>
        <tr>
            <td>Tempat Lahir</td>
            <td>Toy Story</td>
        </tr>
        <tr>
            <td>Tanggal Lahir</td>
            <td>29 july 2003</td>
        </tr>
        <tr>
            <td>Alamat:</td>
            <td>Tokyo, Jepang</td>
        </tr>
    </table>
   <b> <a href="ktp">Kembali</a></b>
</body>

</html>